version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Choose either one of the orbs below
  # welcome: circleci/welcome-orb@0.4.1
  aws-cli: circleci/aws-cli@2.0.3
jobs:
  # create_infrastructure:
  #     docker:
  #       - image: amazon/aws-cli
  #     steps:
  #       - checkout
  #       - run:
  #           name: Create Cloudformation Stack
  #           command: |
  #             aws cloudformation deploy \
  #               --template-file template.yml \
  #               --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
  #               --region us-east-1
  
  configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
              # You can get this ID in the section where you registered the SSH Key
              fingerprints: ["96:48:0c:34:6a:14:b5:a9:7a:5a:7b:8a:2d:8e:41:20"] 
      - run:
          name: Install Ansible
          command: |
            apk add --update ansible
      - run:
          name: Install openssh # resolves {"changed": false, "msg": "unpack requires a buffer of 4 bytes", "unreachable": true}
          command: | 
             apk add openssh-client
      - run:
          name: Run Playbook and Configure server
          command: |
            ansible-playbook -vvvv -i ~/inventory.txt -c ssh playbook.yml

workflows:
  my_workflow:
    jobs:
      # - create_infrastructure
      - configure_infrastructure